# Generated by Django 4.0.4 on 2022-05-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_menu',
            new_name='OrderMenu',
        ),
    ]
