# Generated by Django 4.0.4 on 2022-05-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_delivery_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_finish',
            field=models.BooleanField(default=0),
        ),
    ]
