# Generated by Django 4.0.4 on 2022-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_msg',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
